version: '3.8'
services:
 
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    
    environment:
      - MYSQL_ROOT_PASSWORD="1234"
      - MYSQL_DATABASE="twitter_db"
    ports:
      - 3355:3355
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
      - some-redis
    build: 
      context: "./"
      dockerfile: "Dockerfile"
    
    ports:
      - 3000:3000
    environment:
      - DB_HOST=mysqldb
      - DB_USER="root"
      - DB_PASSWORD="1234"
      - DB_NAME="twitter_db"
      - DB_PORT="3355"
    stdin_open: true
    tty: true
  some-redis:
    image: redis
    ports:
      - 6379:6379

volumes: 
  db: