version: "3"

services:
  some-redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - webnet 

  twitter_db:
    image: mysql:5.7
    ports:
      - 3355:3355
    networks:
      - webnet  
    environment:
      MYSQL_DATABASE: twitter_db
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: root

networks:
  webnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.20.0.0/16"
          gateway: "10.20.0.1"
